version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: /tmp
    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/artifacts;
            export PYTHONPATH=.;
            python tests/test_normalizer.py;

      - store_artifacts:
          path: /tmp/artifacts
          destination: /tmp/artifacts
