version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/tmp
    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command: |
            python -m unittest discover -s tests

      - store_artifacts:
          path: ~/tmp
          destination: ~/tmp
